# Generated by Django 4.2 on 2023-05-03 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_employee_employee_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcenter',
            name='description',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
