# Generated by Django 4.2 on 2023-05-03 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_shoppingcenter_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcenter',
            name='description',
        ),
        migrations.AddField(
            model_name='shoppingcenter_product',
            name='description',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
